name: Deployment

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl

      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-

      - run: |
          echo "DATABASE_URL=\"${{ secrets.DATABASE_URL }}\"" >> .env
          echo "JWT_SECRET=\"${{ secrets.JWT_SECRET }}\"" >> .env

      - run: |
          cross -V || cargo install cross --git https://github.com/cross-rs/cross
          cross build --release --target x86_64-unknown-linux-musl

      - uses: docker/login-action@v2
        with:
          registry: https://${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: ${{ secrets.DOCKER_REGISTRY }}/llr/sync:latest
          platforms: linux/amd64

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_REGISTRY }}/llr/sync:latest
            docker stop llr_sync || true
            docker rm llr_sync || true
            docker run -d --name llr_sync --restart always -p 7100:8080 ${{ secrets.DOCKER_REGISTRY }}/llr/sync:latest
