name: Deploy Image

on:
  workflow_run:
    workflows: ["Build and Push Image"]
    types:
      - completed
  workflow_dispatch:

env:
  DOCKER_TAG: ghcr.io/${{ github.repository }}:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull ${{ env.DOCKER_TAG }}
            docker stop llr_sync || true
            docker rm llr_sync || true
            docker run -d --name llr_sync --restart always -p 7100:8080 --env-file ~/envs/llr_sync.env ${{ env.DOCKER_TAG }}
